// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctclmbrymczduwnncnnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Y2xtYnJ5bWN6ZHV3bm5jbm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTMzNjMsImV4cCI6MjA2MDcyOTM2M30.u7qNEGwIf23IGmaOM544Cg85kNV7HBRxNf3VuviP8vU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);